name: Build(ARM64)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM 22
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y llvm-22 llvm-22-dev mlir-22-tools libmlir-22-dev clang-22 ninja-build

      - name: Build with CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_PREFIX_PATH=/usr/lib/llvm-22 -DCMAKE_C_COMPILER=/usr/bin/clang-22 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-22 -G Ninja
          cmake --build build

      - name: Run Hello World test
        run: |
          output=$(./build/bin/helloworld)
          echo "$output"
          echo "$output" | grep -q "Hello, World!"

      - name: Run MLIR file test
        run: |
          ./build/bin/hello-opt test/hello_world.mlir -emit=mlir-llvm
          ./build/bin/hello-opt test/hello_world.mlir -emit=llvm
          ./build/bin/hello-opt test/hello_world.mlir